name: Build Armbian HC4 Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_branch:
        description: 'Kernel branch'
        required: false
        default: 'current'
        type: choice
        options:
          - current
          - edge
          - legacy
      release:
        description: 'Ubuntu/Debian release'
        required: false
        default: 'jammy'
        type: choice
        options:
          - jammy
          - noble
          - bookworm
          - trixie
  push:
    branches: [ main, master ]
  schedule:
    # Run weekly on Monday at 2 AM UTC
    - cron: '0 2 * * 1'

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Build Armbian Kernel for Odroid HC4
        uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_target: "kernel"
          armbian_board: "odroidhc4"
          armbian_kernel_branch: ${{ github.event.inputs.kernel_branch || 'current' }}
          armbian_release: ${{ github.event.inputs.release || 'jammy' }}
          armbian_compress: "sha,deb,xz"
          armbian_runner_clean: "true"
          armbian_release_tittle: "Armbian Kernel for Odroid HC4"
          armbian_release_body: |
            ## Armbian Kernel Build for Odroid HC4

            **Board:** Odroid HC4 (meson-sm1/meson64 family)
            **Kernel Branch:** ${{ github.event.inputs.kernel_branch || 'current' }}
            **Release:** ${{ github.event.inputs.release || 'jammy' }}
            **Build Date:** ${{ github.run_id }}

            ### Installation

            Download the `.deb` packages and install on your Odroid HC4:

            ```bash
            # Install kernel packages
            sudo dpkg -i linux-image-*.deb
            sudo dpkg -i linux-headers-*.deb
            sudo dpkg -i linux-dtb-*.deb

            # Update boot configuration
            sudo update-initramfs -u -k all
            sudo reboot
            ```

            Built with [Armbian Build Framework](https://github.com/armbian/build)
